### ISSUE TITLE
عدم تغییر وضعیت

### ISSUE THREAD

**Issue by rayshman** [idpay/idpay-restrict-content-plugin#6]
سلام و خسته نباشید 
در استفاده از پلاگین شما من به یه مشکلی برخورد کردم و اون اینکه 
بعد از پرداخت صحیح و درست که به سایت بازگشت داده میشه فاکتور ایجاد میشه و همه چیز درسته 
فقط پلاگین وضعیت کاربر رو تغییر نمیده و وضعیت کاربر در همون پلن قدیم میمونه

**Comment by mohammad-malekpaeen** [comment]
با سلام صحیح می فرمایید . افزونه بروز شده . لطفا آپدیت نمایید
@rayshman
